BASE_API_URL="https://na1.api.riotgames.com"
SUMMONER_API_URL = "/lol/summoner/v4/summoners/by-name/{summonerName}"
SPECTATOR_API_URL = "/lol/spectator/v4/active-games/by-summoner/{encryptedSummonerId}"
LEAGUE_API_URL = "/lol/league/v4/entries/by-summoner/{encryptedSummonerId}"
MATCH_API_URL = "/lol/match/v4/matches/{matchId}"
