RANKED_SOLO_QUEUE_ID = 420
TIERS = ["IRON", "BRONZE", "SILVER", "GOLD", "PLATINUM", "EMERALD", "DIAMOND", "MASTER", "GRANDMASTER", "CHALLENGER"]
DIVISIONS = ["IV", "III", "II", "I"]
RANKED_SOLO_QUEUE_TYPE = "RANKED_SOLO_5x5"
API_KEY_HEADER = "X-Riot-Token"
TIMEZONE_DELTA = -4
GAME_CHECK_THREAD_NAME = "InGameChecker"
HEALTH_CHECK_THREAD_NAME = "HealthChecker"
